//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HubunganKeluarga
    {
        public HubunganKeluarga()
        {
            this.RiwayatPenyakitKeluarga = new HashSet<RiwayatPenyakitKeluarga>();
        }
    
        public byte ID { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<RiwayatPenyakitKeluarga> RiwayatPenyakitKeluarga { get; set; }
    }
}
