//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JalurMasuk
    {
        public JalurMasuk()
        {
            this.MahasiswaDiploma = new HashSet<MahasiswaDiploma>();
            this.MahasiswaDoktor = new HashSet<MahasiswaDoktor>();
            this.MahasiswaMagister = new HashSet<MahasiswaMagister>();
            this.MahasiswaSarjana = new HashSet<MahasiswaSarjana>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public string Keterangan { get; set; }
        public string TahunBerlaku { get; set; }
    
        public virtual ICollection<MahasiswaDiploma> MahasiswaDiploma { get; set; }
        public virtual ICollection<MahasiswaDoktor> MahasiswaDoktor { get; set; }
        public virtual ICollection<MahasiswaMagister> MahasiswaMagister { get; set; }
        public virtual ICollection<MahasiswaSarjana> MahasiswaSarjana { get; set; }
    }
}
