//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JenisPegawai
    {
        public int ID { get; set; }
        public Nullable<int> disJenisPegawai { get; set; }
    
        public virtual Dosen Dosen { get; set; }
        public virtual Pegawai Pegawai { get; set; }
        public virtual Tendik Tendik { get; set; }
    }
}
