//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kecamatan
    {
        public Kecamatan()
        {
            this.RumahSakit = new HashSet<RumahSakit>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public int KotaKabupatenID { get; set; }
    
        public virtual KotaKabupaten KotaKabupaten { get; set; }
        public virtual ICollection<RumahSakit> RumahSakit { get; set; }
    }
}
