//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klinik
    {
        public Klinik()
        {
            this.RekamMedik = new HashSet<RekamMedik>();
            this.Kunjungan = new HashSet<Kunjungan>();
            this.PengeluaranObat = new HashSet<PengeluaranObat>();
            this.PengeluaranObat1 = new HashSet<PengeluaranObat>();
            this.StokObat = new HashSet<StokObat>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<RekamMedik> RekamMedik { get; set; }
        public virtual ICollection<Kunjungan> Kunjungan { get; set; }
        public virtual ICollection<PengeluaranObat> PengeluaranObat { get; set; }
        public virtual ICollection<PengeluaranObat> PengeluaranObat1 { get; set; }
        public virtual ICollection<StokObat> StokObat { get; set; }
    }
}
