//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kunjungan
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
        public int OrangID { get; set; }
        public Nullable<int> NoUrut { get; set; }
        public Nullable<bool> StatusPanggil { get; set; }
        public Nullable<int> LokasiklinikID { get; set; }
        public string Ket { get; set; }
    
        public virtual Orang Orang { get; set; }
        public virtual Klinik Klinik { get; set; }
    }
}
