//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MahasiswaDiploma
    {
        public int ID { get; set; }
        public string NIM { get; set; }
        public Nullable<int> ProgramKeahlianID { get; set; }
        public int JalurMasukID { get; set; }
        public Nullable<System.DateTime> TanggalMasuk { get; set; }
        public Nullable<int> BatasStudi { get; set; }
        public Nullable<int> SumberBiaya { get; set; }
        public Nullable<int> Beasiswa { get; set; }
        public Nullable<int> BPMP { get; set; }
        public string PembimbingAkademik { get; set; }
        public string PindahanPT { get; set; }
        public Nullable<int> TahunMasuk { get; set; }
    
        public virtual Mahasiswa Mahasiswa { get; set; }
        public virtual JalurMasuk JalurMasuk { get; set; }
    }
}
