//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MahasiswaDoktor
    {
        public int ID { get; set; }
        public string NIM { get; set; }
        public int MayorID { get; set; }
        public int JalurMasukID { get; set; }
        public Nullable<System.DateTime> TanggalMasuk { get; set; }
        public Nullable<int> TahunMasuk { get; set; }
        public Nullable<int> BatasStudi { get; set; }
        public Nullable<byte> AwalSemester { get; set; }
        public string GelarDepan { get; set; }
        public string GelarBelakang { get; set; }
        public Nullable<byte> StatusVerifikasi { get; set; }
        public Nullable<byte> PindahMayor { get; set; }
    
        public virtual Mahasiswa Mahasiswa { get; set; }
        public virtual JalurMasuk JalurMasuk { get; set; }
    }
}
