//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mstDokter
    {
        public int PegawaiID { get; set; }
        public Nullable<System.DateTime> TMT { get; set; }
        public Nullable<System.DateTime> TST { get; set; }
        public Nullable<bool> StatusAktif { get; set; }
    
        public virtual Pegawai Pegawai { get; set; }
    }
}
