//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MutasiPegawai
    {
        public int ID { get; set; }
        public int PegawaiID { get; set; }
        public int StrukturOrganisasiID { get; set; }
        public string NomorSK { get; set; }
        public Nullable<System.DateTime> TMT { get; set; }
        public Nullable<System.DateTime> TanggalEntri { get; set; }
        public Nullable<byte> StatusAktif { get; set; }
        public string MutasiPegawaiBKey { get; set; }
    
        public virtual Pegawai Pegawai { get; set; }
    }
}
