//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obat
    {
        public Obat()
        {
            this.ResepObat = new HashSet<ResepObat>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public Nullable<int> SatuanObatID { get; set; }
        public Nullable<int> GolonganObatID { get; set; }
        public string Kegunaan { get; set; }
    
        public virtual ICollection<ResepObat> ResepObat { get; set; }
        public virtual GolonganObat GolonganObat { get; set; }
        public virtual SatuanObat SatuanObat { get; set; }
    }
}
