//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pegawai
    {
        public Pegawai()
        {
            this.MutasiPegawai = new HashSet<MutasiPegawai>();
            this.RekamMedik = new HashSet<RekamMedik>();
        }
    
        public int ID { get; set; }
        public string GelarDepan { get; set; }
        public string GelarBelakang { get; set; }
        public int StatusPegawaiID { get; set; }
        public int StatusKepegawaianID { get; set; }
        public string Inisial { get; set; }
        public string NomorKTP { get; set; }
        public string NomorRekening { get; set; }
        public string NPWP { get; set; }
    
        public virtual ICollection<MutasiPegawai> MutasiPegawai { get; set; }
        public virtual ICollection<RekamMedik> RekamMedik { get; set; }
        public virtual JenisPegawai JenisPegawai { get; set; }
        public virtual Orang Orang { get; set; }
        public virtual mstDokter mstDokter { get; set; }
    }
}
