//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PengadaanObat
    {
        public int ID { get; set; }
        public Nullable<int> ObatID { get; set; }
        public Nullable<int> Jumlah { get; set; }
        [Required(ErrorMessage = "Tidak boleh kosong")]
        public Nullable<System.DateTime> Tanggal { get; set; }
        public Nullable<int> HET { get; set; }
        public Nullable<int> HargaAktual { get; set; }
        public int PenyediaObatID { get; set; }
    
        public virtual Obat Obat { get; set; }
        public virtual PenyediaObat PenyediaObat { get; set; }
    }
}
