//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Penyakit
    {
        public Penyakit()
        {
            this.RiwayatPenyakit = new HashSet<RiwayatPenyakit>();
            this.RiwayatPenyakitKeluarga = new HashSet<RiwayatPenyakitKeluarga>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
        public string NamaIlmiah { get; set; }
        public Nullable<int> KelompokPenyakitID { get; set; }
    
        public virtual ICollection<RiwayatPenyakit> RiwayatPenyakit { get; set; }
        public virtual ICollection<RiwayatPenyakitKeluarga> RiwayatPenyakitKeluarga { get; set; }
        public virtual KelompokPenyakit KelompokPenyakit { get; set; }
    }
}
