//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RekamMedik
    {
        public RekamMedik()
        {
            this.ResepObat = new HashSet<ResepObat>();
            this.PengeluaranObat = new HashSet<PengeluaranObat>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PasienID { get; set; }
        public Nullable<System.DateTime> Tanggal { get; set; }
        public string AnamnesaDiagnosa { get; set; }
        public string Therapie { get; set; }
        public Nullable<int> LokasiklinikID { get; set; }
        public Nullable<int> DokterID { get; set; }
    
        public virtual Klinik Klinik { get; set; }
        public virtual Orang Orang { get; set; }
        public virtual Pegawai Pegawai { get; set; }
        public virtual ICollection<ResepObat> ResepObat { get; set; }
        public virtual Rujukan Rujukan { get; set; }
        public virtual ICollection<PengeluaranObat> PengeluaranObat { get; set; }
    }
}
