//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResepObat
    {
        public int ID { get; set; }
        public Nullable<int> RekamMedikID { get; set; }
        public Nullable<int> ObatID { get; set; }
        public Nullable<int> Jumlah { get; set; }
        public Nullable<int> SatuanObatID { get; set; }
        public string Pemakaian { get; set; }
        public Nullable<bool> isDihabiskan { get; set; }
        public Nullable<bool> isSetelahMakan { get; set; }
        public string NoResep { get; set; }
    
        public virtual RekamMedik RekamMedik { get; set; }
        public virtual Obat Obat { get; set; }
        public virtual SatuanObat SatuanObat { get; set; }
    }
}
