//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RiwayatPenyakit
    {
        public int ID { get; set; }
        public int PasienID { get; set; }
        public int PenyakitID { get; set; }
        public int Tahun { get; set; }
    
        public virtual Orang Orang { get; set; }
        public virtual Penyakit Penyakit { get; set; }
    }
}
