//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rujukan
    {
        public int RekamMedikID { get; set; }
        public int RumahSakitID { get; set; }
        public string Bagian { get; set; }
    
        public virtual RekamMedik RekamMedik { get; set; }
        public virtual RumahSakit RumahSakit { get; set; }
    }
}
