//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SipoliDev5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SatuanObat
    {
        public SatuanObat()
        {
            this.ResepObat = new HashSet<ResepObat>();
            this.Obat = new HashSet<Obat>();
        }
    
        public int ID { get; set; }
        public string Nama { get; set; }
    
        public virtual ICollection<ResepObat> ResepObat { get; set; }
        public virtual ICollection<Obat> Obat { get; set; }
    }
}
